=== ellenm1/medbiq/shortordercook/competencyframework.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 sp1 (http://www.altova.com) by Valerie Smothers (Johns Hopkins) -->
<!--Generated by Turbo XML 2.4.0.100. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns="http://ns.medbiq.org/competencyframework/v1/" xmlns:lom="http://ltsc.ieee.org/xsd/LOM" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ns.medbiq.org/competencyframework/v1/" elementFormDefault="qualified">
	<xsd:import namespace="http://ltsc.ieee.org/xsd/LOM" schemaLocation="http://ns.medbiq.org/lom/healthcarelom.xsd"/>
	<xsd:import namespace="http://www.w3.org/1999/xhtml" schemaLocation="http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd"/>
	<!-- Copyright Â© 2011 MedBiquitous Consortium. All Rights Reserved. http://www.medbiq.org -->
	<!-- Users are bound by the terms of the MedBiquitous Consortium XML Public License and Terms of Use -->
	<!-- Modified 9 December 2011 -->
	<xsd:simpleType name="NonNullString">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RelationshipType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="http://www.w3.org/2004/02/skos/core#broader"/>
			<xsd:enumeration value="http://www.w3.org/2004/02/skos/core#narrower"/>
			<xsd:enumeration value="http://www.w3.org/2004/02/skos/core#related"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="IdentifierType">
		<xsd:sequence>
			<xsd:element name="Catalog" type="NonNullString"/>
			<xsd:element name="Entry" type="NonNullString"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="RelationType">
		<xsd:sequence>
			<xsd:element name="Reference1" type="IdentifierType"/>
			<xsd:element name="Relationship" type="RelationshipType"/>
			<xsd:element name="Reference2" type="IdentifierType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="SupportingInformationType">
		<xsd:choice>
			<xsd:element name="Link" type="xsd:anyURI"/>
			<xsd:element ref="xhtml:div"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="CompetencyFrameworkType">
		<xsd:sequence>
			<xsd:element ref="lom:lom"/>
			<xsd:element name="EffectiveDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="RetiredDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="Replaces" type="xsd:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="IsReplacedBy" type="xsd:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="SupportingInformation" type="SupportingInformationType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Includes" type="IdentifierType" maxOccurs="unbounded"/>
			<xsd:element name="Relation" type="RelationType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="CompetencyFramework" type="CompetencyFrameworkType"/>
</xsd:schema>

=== ellenm1/medbiq/shortordercook/shortordercook_epas.xml
<?xml version="1.0" encoding="UTF-8"?>
<CompetencyFramework xmlns="http://ns.medbiq.org/competencyframework/v1/" xmlns:lom="http://ltsc.ieee.org/xsd/LOM" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.medbiq.org/competencyframework/v1/ competencyframework.xsd">
	<lom:lom>
		<lom:general>
			<lom:identifier>
				<lom:catalog>URI</lom:catalog>
				<lom:entry>http://www.example.org/short_order_cook_epas_v1</lom:entry>
			</lom:identifier>
			<lom:title>
				<lom:string>Short Order Cook Entrustable Professional Activities</lom:string>
			</lom:title>
			<lom:description>
				<lom:string language="en">The Entrustable Professional Activities (EPAs) of a short order cook. Learners will be entrusted to perform these activities during their training.</lom:string>
			</lom:description>
		</lom:general>
		<lom:lifeCycle>
			<lom:version>
				<lom:string>1.0</lom:string>
			</lom:version>
			<lom:contribute>
				<lom:entity>BEGIN:VCARD\nFN:Center for Really Good CooksEND:VCARD</lom:entity>
				<lom:role>
					<lom:source>LOMv1.0</lom:source>
					<lom:value>publisher</lom:value>
				</lom:role>
			</lom:contribute>
		</lom:lifeCycle>
		<lom:rights>
			<lom:copyrightAndOtherRestrictions>
				<lom:source>LOMv1.0</lom:source>
				<lom:value>yes</lom:value>
			</lom:copyrightAndOtherRestrictions>
			<lom:description>
				<lom:string language="en">Creative Commons Attribution 3.0 Unported license, http://creativecommons.org/licenses/by/3.0/</lom:string>
			</lom:description>
		</lom:rights>
	</lom:lom>
	<Includes>
		<Catalog>URI</Catalog>
		<Entry>http://www.example.org/shortordercookepas/e1</Entry>
	</Includes>
	<Includes>
		<Catalog>URI</Catalog>
		<Entry>http://www.example.org/shortordercookepas/e2</Entry>
	</Includes>	
	<Includes>
		<Catalog>URI</Catalog>
		<Entry>http://www.example.org/shortordercookepas/e3</Entry>
	</Includes>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e1</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c1</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e1</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c2</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e1</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c3</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e1</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c4</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e1</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c5</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e1</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c6c</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e1</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c7a</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e2</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c2b</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e2</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c3</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e2</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c4</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e2</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c5</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e2</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c6d</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e2</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c7a</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e3</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c6a</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e3</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c6b</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e3</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c6e</Entry>
		</Reference2>
	</Relation>
	<Relation>
		<Reference1>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookepas/e3</Entry>
		</Reference1>
		<Relationship>http://www.w3.org/2004/02/skos/core#related</Relationship>
		<Reference2>
			<Catalog>URI</Catalog>
			<Entry>http://www.example.org/shortordercookcompetencies/c7b</Entry>
		</Reference2>
	</Relation>
</CompetencyFramework>
